export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const RESET_REGISTRATION = 'RESET_REGISTRATION';

export const CHANGE_VALUE = 'CHANGE_VALUE';
export const ADD_COUNTER = 'ADD_COUNTER';
export const DELETE_COUNTER = 'DELETE_COUNTER';
export const RESET_COUNTERS = 'RESET_COUNTERS';
